version: '3'
services:
  web:
    build: # build from the dockerfile in the current folder (use .)
      context: . # where the files should be pulled from
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app # map the node_modules folder outside the container to ./app inside the container
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
